version: '3.8'

services:
  # 后端API服务
  api:
    build: .
    container_name: waste_transport_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/waste_transport
    depends_on:
      - db
    networks:
      - waste_transport_network

  # 数据库服务
  db:
    image: postgres:14
    container_name: waste_transport_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=waste_transport
    networks:
      - waste_transport_network

networks:
  waste_transport_network:
    driver: bridge

volumes:
  postgres_data: